# Hardware Subsystems
CONFIG_DISPLAY=y
CONFIG_SPI=y
CONFIG_MIPI_DBI=y

# Display Driver
CONFIG_ST7735R=y

# LVGL Graphics
CONFIG_LVGL=y
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_Z_VDB_SIZE=100
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=y
